config/routes.rb
Rails.application.routes.draw do

  resources :blogs do
  	resources :entries do
  	  resources :comments, only: [:index, :search2, :new, :create, :destroy] do
  	    collection do
          get 'search1'
        end
        member do
          get 'search2'
        end
  	  end
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_many :entries, dependent: :destroy
    validates :title, presence: { message: 'は必須入力です。'}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :entry
end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :blog
    has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :set_blog, only: [:update, :destroy]

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
        respond_to do |format|
        if @blog.save
            #format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
            format.html { redirect_to blogs_path, notice: 'Blog was successfully created.' }
        else
            format.html { render :new }
        end
    end
    #if @blog.save
    #    render :show, status: :created, location: @blog
    #else
    #    render :new
    #end
  end

  def update
    if @blog.update(blog_params)
        render :show, status: :ok, location: @blog
    else
        render :edit
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
        format.html { redirect_to blogs_url, notice: '削除されました' }
    end
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
    #@blog = Blog.where("id = #{params[:id]}").first
  end

  def blog_params
    params.require(:blog).permit(:title)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def search1
  end

  def search2
    com = Comment.find(params[:id])
    com.status = "approved"
    com.save
    @comment = Comment.find(params[:id])
    redirect_to blog_entry_comments_path

    @entry = Entry.find(params[:entry_id])
    @blog = Blog.find(params[:blog_id])
    
    NoticeMailer.sendmail_confirm(@blog, @entry, @comment).deliver
  end

  def index
    @comments = Entry.joins(:comments).merge(Comment.where(entry_id: params[:entry_id])).select("comments.*")
    @entry = Entry.find(params[:entry_id])
    @blog = Blog.find(params[:blog_id])
  end

  def show
  end

  def edit
  end

  def new
    @blog = Blog.find(params[:blog_id])
    @entry = Entry.find(params[:entry_id])
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(create_params)
      if @comment.save
        redirect_to blog_entry_comments_path, notice: 'Comment was successfully created.'
      else
        render :new
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to blog_entry_comments_path, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def create_params
    params.require(:comment).permit(:body, :status).merge(entry_id: params[:entry_id])
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Blog.joins(:entries).merge(Entry.where(blog_id: params[:blog_id])).select("entries.*")
    @blog = Blog.find(params[:blog_id])
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @blog  = Blog.find(params[:blog_id])
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
    @blog = Blog.find(params[:blog_id])
  end

  # POST /entries
  # POST /entries.json
  def create
    #@entry = Entry.new(entry_params)
    @entry = Entry.new(create_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to blog_entries_path, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to blog_entries_path, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to blog_entries_path, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :body)
    end

    def create_params
        params.require(:entry).permit(:title, :body).merge(blog_id: params[:blog_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/blogs/create.html.erb
<h1>Blogs#create</h1>
<p>Find me in app/views/blogs/create.html.erb</p>

app/views/blogs/destroy.html.erb
<h1>Blogs#destroy</h1>
<p>Find me in app/views/blogs/destroy.html.erb</p>

app/views/blogs/edit.html.erb
<h1>Blogs#edit</h1>

<%= form_with(model: @blog, local: true) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to '戻る', blogs_path %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>
<table>
    <head>
        <tr>
            <th>ID</th>    
            <th>タイトル</th>
            <th colspan="4"></th>
        </tr>
    </head>
    <body>
        <% @blogs.each do |blog| %>
        <tr>
            <td><%= blog.id %></td>
            <td><%= blog.title %></td>
            <td><%= link_to 'Show', blog %></td>
            <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
            <td><%= link_to 'Destroy', blog, method: :delete, data: {confirm: '削除していいですか？' } %></td>
            <td><%= link_to 'To Entry', blog_entries_path(blog) %></td>
            </tr>
        <% end %>
    </body>
</table>
<br>
<%= link_to '新規', new_blog_path %>

app/views/blogs/new.html.erb
<h1>Blogs#new</h1>

<%= form_with(model: @blog, local: true) do |form| %>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
  
        <ul>
        <% @blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<h1>Blogs#show</h1>

<p> Title:
    <%= @blog.title %>
</p>

<%= link_to 'Back', blogs_path %>

app/views/blogs/update.html.erb
<h1>Blogs#update</h1>
<p>Find me in app/views/blogs/update.html.erb</p>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= form_with(model: @comment, url: [@blog, @entry, @comment], local: true) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, value: 'approved' %>
  </div>

  <div class="actions">
    <%= form.submit "更新" %>
  </div>
<% end %>

<%= link_to '戻る', blog_entry_comments_path %>

app/views/comments/index.html.erb
<h1>Blog / Entry / Comments</h1>

<h4>id : <%= @blog.id %> </h4> 
<h4>Title : <%= @blog.title %> </h4> 
<h4>id : <%= @entry.id %></h4>
<h4>Title : <%= @entry.title %></h4>
<h4>Body : <%= @entry.body %></h4>

<table>
    <thead>
        <tr>
            <th>id</th>
            <th>body</th>
            <th>status</th>
            <th>entry_id</th>
            <th colspan="1"></th>
            </body>
        </tr>
    </thead>
    <tbody>
        <% @comments.each do |comment| %>
            <tr>
                <% if comment.status == 'approved' %>
                    <td><%= comment.id %></td>
                    <td><%= comment.body %></td>
                    <td><%= comment.status %></td>
                    <td><%= comment.entry_id %></td>
                <% else %>
                    <td><%= comment.id %></<td>
                    <td></td>
                    <td><%= link_to 'unapproved', search2_blog_entry_comment_path(:id => comment.id) %></td>   
                    <td><%= comment.entry_id %></td>
                <% end %>
                <td><%= link_to 'Destroy', blog_entry_comment_path(@blog, @entry, comment), method: :delete, data: { confirm: '削除してよろしいですか?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to '新規', new_blog_entry_comment_path %> | <%= link_to '戻る', blog_entries_path %> 

app/views/comments/new.html.erb
<h1>Comments#new</h1>

<%= form_with(model: [@blog, @entry, @comment], url: [@blog, @entry, @comment], local: true) do |form| %>
    <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
  
        <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  
    <div class="field">
      <%= form.label :status %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

<%= link_to '戻る', blog_entry_comments_path %>

app/views/comments/search2.html.erb
<h1>Comments#search2</h1>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= form_with(model: [@blog, @entry], url: [@blog, @entry], local: true) do |form| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to '戻る', blog_entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog/Entries</h1>

<h3>id: <%= @blog.id %></h3>
<h3>Title: <%= @blog.title %></h3>


<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Title</th>
      <th>Body</th>
      <th>blog_id</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.id %></td>
        <td><%= entry.title %></td>
        <td><%= entry.body %></td>
        <td><%= entry.blog_id %></td>
        <td><%= link_to 'Show', blog_entry_path(@blog, entry) %></td>
        <td><%= link_to 'Edit', edit_blog_entry_path(@blog, entry) %></td>
        <td><%= link_to 'Destroy', blog_entry_path(@blog, entry), method: :delete, data: { confirm: '削除してよろしいですか?' } %></td>
        <td><%= link_to 'To Comment', blog_entry_comments_path(@blog, entry) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to '新規', new_blog_entry_path %> | <%= link_to '戻る', blogs_path %> 

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= form_with(model: [@blog, @entry], url: [@blog, @entry], local: true) do |form| %>
    <% if @entry.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
  
        <ul>
        <% @entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

<%= link_to 'Back', blog_entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @entry.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @entry.body %>
</p>

<%= link_to 'Back', blog_entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloRailsA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>